### ISSUE TITLE
Bug Report: Bottleneck

### ISSUE THREAD

**Issue by JoshuaRogan** [JoshuaRogan/genetics#37]
I also noticed some bugs, as described below.

For bottleneck generations, the generations option needs to expand to the maximum number of generations selected by the user (currently it maxes out at 500)

**Comment by AlburIvan** [comment]
Am I missing something here or its solved? 

### Simulation Graph
![image](https://user-images.githubusercontent.com/10523232/231503221-97771920-0de5-4f60-9ee0-c4b92f223dc3.png)

### Simulation Values
![image](https://user-images.githubusercontent.com/10523232/231503154-2ae1b09f-569e-45a5-a8f7-c6ce279a20b5.png)


###  Final frequency of genotype A1A2
![image](https://user-images.githubusercontent.com/10523232/231503367-1246384c-b37d-456f-b970-30062bf470fd.png)

**Comment by AlburIvan** [comment]
Since URLs are live:

[These settings already selected](https://epic-shaw-a67b5a.netlify.app/individual?t=10000&numSims=1&p=0.5&N=5000&Nb=1&WAA=0.800&WAa=1.000&Waa=0.300&s=0&h=1&mu=0&nu=0&mu-exp=-5&nu-exp=-5&m=0.200&pm=0.5&F=0.200&assortMating=0.150&gen-to-over-start=400&gen-to-over-end=450&BNb=500)
